
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public AZUL.TbPiece TbPiece {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbPiece = new AZUL.TbPiece(loader("azul_tbpiece"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbPiece.ResolveRef(this);
    }
}

}

