// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from game.proto</summary>
public static partial class GameReflection {

  #region Descriptor
  /// <summary>File descriptor for game.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpnYW1lLnByb3RvIpoBChZOZXRCb2FyZEdhbWVQbGF5ZXJEYXRhEhgKEHBs",
          "YXllcl9jbGllbnRfaWQYASABKAUSFgoOcGxheWVyX3NlYXRfaWQYAiABKAUS",
          "IwoLcGxheWVyX3R5cGUYAyABKA4yDi5OZXRQbGF5ZXJUeXBlEhMKC3BsYXll",
          "cl9uYW1lGAQgASgJEhQKDHBsYXllcl9zY29yZRgFIAEoBSJSCg1HYW1lUmVz",
          "dWx0TnRmEhIKCndpbm5lcl9pZHMYASADKAUSLQoMcGxheWVyX2RhdGFzGAIg",
          "AygLMhcuTmV0Qm9hcmRHYW1lUGxheWVyRGF0YSJHCgxGc21DaGFuZ2VOdGYS",
          "IwoJbmV3X3N0YXRlGAEgASgOMhAuTmV0RnNtU3RhdGVUeXBlEhIKCnN0YXRl",
          "X2RhdGEYAiABKAkqUAoNTmV0UGxheWVyVHlwZRIUChBQTEFZRVJfVFlQRV9O",
          "T05FEAASFQoRUExBWUVSX1RZUEVfSFVNQU4QARISCg5QTEFZRVJfVFlQRV9B",
          "SRACKukBCg9OZXRGc21TdGF0ZVR5cGUSEgoORlNNX1NUQVRFX05PTkUQABIS",
          "Cg5GU01fU1RBVEVfSURMRRABEiEKHUZTTV9TVEFURV9TRUxFQ1RfRklSU1Rf",
          "UExBWUVSEAISGAoURlNNX1NUQVRFX0RFQUxfQ0FSRFMQAxIZChVGU01fU1RB",
          "VEVfUExBWUVSX1RVUk4QBBIeChpGU01fU1RBVEVfR0FNRV9TVEVQX1NFVFRM",
          "RRAFEhoKFkZTTV9TVEFURV9GSU5BTF9TRVRUTEUQBhIaChZGU01fU1RBVEVf",
          "U0VUVExFX1BBTkVMEAdiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetPlayerType), typeof(global::NetFsmStateType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::NetBoardGamePlayerData), global::NetBoardGamePlayerData.Parser, new[]{ "PlayerClientId", "PlayerSeatId", "PlayerType", "PlayerName", "PlayerScore" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GameResultNtf), global::GameResultNtf.Parser, new[]{ "WinnerIds", "PlayerDatas" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FsmChangeNtf), global::FsmChangeNtf.Parser, new[]{ "NewState", "StateData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum NetPlayerType {
  [pbr::OriginalName("PLAYER_TYPE_NONE")] PlayerTypeNone = 0,
  [pbr::OriginalName("PLAYER_TYPE_HUMAN")] PlayerTypeHuman = 1,
  [pbr::OriginalName("PLAYER_TYPE_AI")] PlayerTypeAi = 2,
}

public enum NetFsmStateType {
  [pbr::OriginalName("FSM_STATE_NONE")] FsmStateNone = 0,
  [pbr::OriginalName("FSM_STATE_IDLE")] FsmStateIdle = 1,
  [pbr::OriginalName("FSM_STATE_SELECT_FIRST_PLAYER")] FsmStateSelectFirstPlayer = 2,
  [pbr::OriginalName("FSM_STATE_DEAL_CARDS")] FsmStateDealCards = 3,
  [pbr::OriginalName("FSM_STATE_PLAYER_TURN")] FsmStatePlayerTurn = 4,
  [pbr::OriginalName("FSM_STATE_GAME_STEP_SETTLE")] FsmStateGameStepSettle = 5,
  [pbr::OriginalName("FSM_STATE_FINAL_SETTLE")] FsmStateFinalSettle = 6,
  [pbr::OriginalName("FSM_STATE_SETTLE_PANEL")] FsmStateSettlePanel = 7,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class NetBoardGamePlayerData : pb::IMessage<NetBoardGamePlayerData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NetBoardGamePlayerData> _parser = new pb::MessageParser<NetBoardGamePlayerData>(() => new NetBoardGamePlayerData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NetBoardGamePlayerData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetBoardGamePlayerData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetBoardGamePlayerData(NetBoardGamePlayerData other) : this() {
    playerClientId_ = other.playerClientId_;
    playerSeatId_ = other.playerSeatId_;
    playerType_ = other.playerType_;
    playerName_ = other.playerName_;
    playerScore_ = other.playerScore_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NetBoardGamePlayerData Clone() {
    return new NetBoardGamePlayerData(this);
  }

  /// <summary>Field number for the "player_client_id" field.</summary>
  public const int PlayerClientIdFieldNumber = 1;
  private int playerClientId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlayerClientId {
    get { return playerClientId_; }
    set {
      playerClientId_ = value;
    }
  }

  /// <summary>Field number for the "player_seat_id" field.</summary>
  public const int PlayerSeatIdFieldNumber = 2;
  private int playerSeatId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlayerSeatId {
    get { return playerSeatId_; }
    set {
      playerSeatId_ = value;
    }
  }

  /// <summary>Field number for the "player_type" field.</summary>
  public const int PlayerTypeFieldNumber = 3;
  private global::NetPlayerType playerType_ = global::NetPlayerType.PlayerTypeNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NetPlayerType PlayerType {
    get { return playerType_; }
    set {
      playerType_ = value;
    }
  }

  /// <summary>Field number for the "player_name" field.</summary>
  public const int PlayerNameFieldNumber = 4;
  private string playerName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PlayerName {
    get { return playerName_; }
    set {
      playerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "player_score" field.</summary>
  public const int PlayerScoreFieldNumber = 5;
  private int playerScore_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlayerScore {
    get { return playerScore_; }
    set {
      playerScore_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NetBoardGamePlayerData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NetBoardGamePlayerData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerClientId != other.PlayerClientId) return false;
    if (PlayerSeatId != other.PlayerSeatId) return false;
    if (PlayerType != other.PlayerType) return false;
    if (PlayerName != other.PlayerName) return false;
    if (PlayerScore != other.PlayerScore) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PlayerClientId != 0) hash ^= PlayerClientId.GetHashCode();
    if (PlayerSeatId != 0) hash ^= PlayerSeatId.GetHashCode();
    if (PlayerType != global::NetPlayerType.PlayerTypeNone) hash ^= PlayerType.GetHashCode();
    if (PlayerName.Length != 0) hash ^= PlayerName.GetHashCode();
    if (PlayerScore != 0) hash ^= PlayerScore.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PlayerClientId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(PlayerClientId);
    }
    if (PlayerSeatId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PlayerSeatId);
    }
    if (PlayerType != global::NetPlayerType.PlayerTypeNone) {
      output.WriteRawTag(24);
      output.WriteEnum((int) PlayerType);
    }
    if (PlayerName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(PlayerName);
    }
    if (PlayerScore != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(PlayerScore);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PlayerClientId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(PlayerClientId);
    }
    if (PlayerSeatId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PlayerSeatId);
    }
    if (PlayerType != global::NetPlayerType.PlayerTypeNone) {
      output.WriteRawTag(24);
      output.WriteEnum((int) PlayerType);
    }
    if (PlayerName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(PlayerName);
    }
    if (PlayerScore != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(PlayerScore);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PlayerClientId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerClientId);
    }
    if (PlayerSeatId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerSeatId);
    }
    if (PlayerType != global::NetPlayerType.PlayerTypeNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerType);
    }
    if (PlayerName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerName);
    }
    if (PlayerScore != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerScore);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NetBoardGamePlayerData other) {
    if (other == null) {
      return;
    }
    if (other.PlayerClientId != 0) {
      PlayerClientId = other.PlayerClientId;
    }
    if (other.PlayerSeatId != 0) {
      PlayerSeatId = other.PlayerSeatId;
    }
    if (other.PlayerType != global::NetPlayerType.PlayerTypeNone) {
      PlayerType = other.PlayerType;
    }
    if (other.PlayerName.Length != 0) {
      PlayerName = other.PlayerName;
    }
    if (other.PlayerScore != 0) {
      PlayerScore = other.PlayerScore;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerClientId = input.ReadInt32();
          break;
        }
        case 16: {
          PlayerSeatId = input.ReadInt32();
          break;
        }
        case 24: {
          PlayerType = (global::NetPlayerType) input.ReadEnum();
          break;
        }
        case 34: {
          PlayerName = input.ReadString();
          break;
        }
        case 40: {
          PlayerScore = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PlayerClientId = input.ReadInt32();
          break;
        }
        case 16: {
          PlayerSeatId = input.ReadInt32();
          break;
        }
        case 24: {
          PlayerType = (global::NetPlayerType) input.ReadEnum();
          break;
        }
        case 34: {
          PlayerName = input.ReadString();
          break;
        }
        case 40: {
          PlayerScore = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class GameResultNtf : pb::IMessage<GameResultNtf>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GameResultNtf> _parser = new pb::MessageParser<GameResultNtf>(() => new GameResultNtf());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GameResultNtf> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameResultNtf() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameResultNtf(GameResultNtf other) : this() {
    winnerIds_ = other.winnerIds_.Clone();
    playerDatas_ = other.playerDatas_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameResultNtf Clone() {
    return new GameResultNtf(this);
  }

  /// <summary>Field number for the "winner_ids" field.</summary>
  public const int WinnerIdsFieldNumber = 1;
  private static readonly pb::FieldCodec<int> _repeated_winnerIds_codec
      = pb::FieldCodec.ForInt32(10);
  private readonly pbc::RepeatedField<int> winnerIds_ = new pbc::RepeatedField<int>();
  /// <summary>
  /// List of winner player IDs
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> WinnerIds {
    get { return winnerIds_; }
  }

  /// <summary>Field number for the "player_datas" field.</summary>
  public const int PlayerDatasFieldNumber = 2;
  private static readonly pb::FieldCodec<global::NetBoardGamePlayerData> _repeated_playerDatas_codec
      = pb::FieldCodec.ForMessage(18, global::NetBoardGamePlayerData.Parser);
  private readonly pbc::RepeatedField<global::NetBoardGamePlayerData> playerDatas_ = new pbc::RepeatedField<global::NetBoardGamePlayerData>();
  /// <summary>
  /// List of player data
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::NetBoardGamePlayerData> PlayerDatas {
    get { return playerDatas_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GameResultNtf);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GameResultNtf other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!winnerIds_.Equals(other.winnerIds_)) return false;
    if(!playerDatas_.Equals(other.playerDatas_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= winnerIds_.GetHashCode();
    hash ^= playerDatas_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    winnerIds_.WriteTo(output, _repeated_winnerIds_codec);
    playerDatas_.WriteTo(output, _repeated_playerDatas_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    winnerIds_.WriteTo(ref output, _repeated_winnerIds_codec);
    playerDatas_.WriteTo(ref output, _repeated_playerDatas_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += winnerIds_.CalculateSize(_repeated_winnerIds_codec);
    size += playerDatas_.CalculateSize(_repeated_playerDatas_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GameResultNtf other) {
    if (other == null) {
      return;
    }
    winnerIds_.Add(other.winnerIds_);
    playerDatas_.Add(other.playerDatas_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          winnerIds_.AddEntriesFrom(input, _repeated_winnerIds_codec);
          break;
        }
        case 18: {
          playerDatas_.AddEntriesFrom(input, _repeated_playerDatas_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 8: {
          winnerIds_.AddEntriesFrom(ref input, _repeated_winnerIds_codec);
          break;
        }
        case 18: {
          playerDatas_.AddEntriesFrom(ref input, _repeated_playerDatas_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FsmChangeNtf : pb::IMessage<FsmChangeNtf>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FsmChangeNtf> _parser = new pb::MessageParser<FsmChangeNtf>(() => new FsmChangeNtf());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FsmChangeNtf> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FsmChangeNtf() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FsmChangeNtf(FsmChangeNtf other) : this() {
    newState_ = other.newState_;
    stateData_ = other.stateData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FsmChangeNtf Clone() {
    return new FsmChangeNtf(this);
  }

  /// <summary>Field number for the "new_state" field.</summary>
  public const int NewStateFieldNumber = 1;
  private global::NetFsmStateType newState_ = global::NetFsmStateType.FsmStateNone;
  /// <summary>
  /// The new state of the FSM
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NetFsmStateType NewState {
    get { return newState_; }
    set {
      newState_ = value;
    }
  }

  /// <summary>Field number for the "state_data" field.</summary>
  public const int StateDataFieldNumber = 2;
  private string stateData_ = "";
  /// <summary>
  /// Additional data related to the state change
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string StateData {
    get { return stateData_; }
    set {
      stateData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FsmChangeNtf);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FsmChangeNtf other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (NewState != other.NewState) return false;
    if (StateData != other.StateData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (NewState != global::NetFsmStateType.FsmStateNone) hash ^= NewState.GetHashCode();
    if (StateData.Length != 0) hash ^= StateData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (NewState != global::NetFsmStateType.FsmStateNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) NewState);
    }
    if (StateData.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(StateData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (NewState != global::NetFsmStateType.FsmStateNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) NewState);
    }
    if (StateData.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(StateData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (NewState != global::NetFsmStateType.FsmStateNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NewState);
    }
    if (StateData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(StateData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FsmChangeNtf other) {
    if (other == null) {
      return;
    }
    if (other.NewState != global::NetFsmStateType.FsmStateNone) {
      NewState = other.NewState;
    }
    if (other.StateData.Length != 0) {
      StateData = other.StateData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          NewState = (global::NetFsmStateType) input.ReadEnum();
          break;
        }
        case 18: {
          StateData = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          NewState = (global::NetFsmStateType) input.ReadEnum();
          break;
        }
        case 18: {
          StateData = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
