
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.AZUL
{

public sealed partial class Piece : Luban.BeanBase
{
    public Piece(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        PieceTokenType = (int)_obj.GetValue("PieceTokenType");
    }

    public static Piece DeserializePiece(JToken _buf)
    {
        return new AZUL.Piece(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly int PieceTokenType;


    public const int __ID__ = -1410743312;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PieceTokenType:" + PieceTokenType + ","
        + "}";
    }
}
}

