syntax = "proto3";

enum NetPlayerType {
    PLAYER_TYPE_NONE = 0;
    PLAYER_TYPE_HUMAN = 1;
    PLAYER_TYPE_AI = 2;
}

enum NetFsmStateType{
    FSM_STATE_NONE = 0;
    FSM_STATE_IDLE = 1;
    FSM_STATE_SELECT_FIRST_PLAYER = 2;
    FSM_STATE_DEAL_CARDS = 3;
    FSM_STATE_PLAYER_TURN = 4;
    FSM_STATE_GAME_STEP_SETTLE = 5;
    FSM_STATE_FINAL_SETTLE = 6;
    FSM_STATE_SETTLE_PANEL = 7;
}

message NetBoardGamePlayerData{
    int32 player_client_id = 1;
    int32 player_seat_id = 2;
    NetPlayerType player_type = 3;
    string player_name = 4;
    int32 player_score = 5;
}

message GameResultNtf{
    repeated int32 winner_ids = 1; // List of winner player IDs
    repeated NetBoardGamePlayerData player_datas = 2; // List of player data
}

message FsmChangeNtf{
    NetFsmStateType new_state = 1; // The new state of the FSM
    string state_data = 2; // Additional data related to the state change
}